zerocracy/zerocracy.github.io

pages/policy.md

Added vacancies details for https://github.com/zerocracy/farm/issues/971 job.

Missed announcement info

---

pages/policy.md

zerocracy/farm#1175 - using 8% instead of 5min

QA bonus changed

---

pages/policy.md

zerocracy/farm#1350 - updated "wallets" section in policy.

Zold wallets

---

pages/faq.md

Mentioned payment for reported bugs.

Added payment for reported bugs

---

pages/policy.md

Fix grammar and spelling typos

Fix grammar and spelling typos in Policy

---

_posts/2018/02/2018-02-22-policy.md

zerocracy/farm#1028 - ARC penalty for long reviews

ARC penalty for long reviews

---

_posts/2018/02/2018-02-22-policy.md

#54 - corrected invitation paragraph

Corrected invitation paragraph

---

_posts/2018/02/2018-02-22-policy.md

zerocracy/farm#1884 - `QA` verdict by `ARC` explained

QA verdict by ARC

---

_posts/2019/01/2019-01-30-project-faq.md

FAQ for new projects

---

_posts/2018/09/2018-09-07-what-is-speed.md

Proofreading "How Long It Takes to Close"

---

_posts/2018/02/2018-02-22-policy.md

Changed `QA` price from 8 minutes to 6

Updated qa price

---

_posts/2018/02/2018-02-22-policy.md

zerocracy/farm#1927 - added reviewer penalty of `-32` points

Reviewer penalty

---

_posts/2018/02/2018-02-22-policy.md

Explained `TST` role for zerocracy/farm#1928 and zerocracy/farm#1889

zerocracy/farm#1928 - TST explained

---

_posts/2018/02/2018-02-22-policy.md

zerocracy/farm#1943 - explained on pause behavior

Explained pause

---

_posts/2019/03/2019-03-18-how-to-become-a-qa.md

New post to explain how to join Zerocracy as QA

Added become-a-qa post

---

_posts/2018/02/2018-02-22-policy.md

zerocracy/farm#1860 - removed paypal payment option from policy

Removed paypal from policy

---

_drafts/ammaratef45.md

Added an article `My life since I discovered Zerocracy`

Added my article

---

_posts/2018/02/2018-02-22-policy.md

zerocracy/farm#1841 - cancel on quit

Cancel jobs on quit

---

_posts/2018/02/2018-02-22-policy.md

zerocracy/farm#1937 - added daysToCloseTask option

Project options daysToCloseTask

---

_posts/2018/06/2018-06-26-faq.md

Using Zerocracy QA as join-helpers as in https://github.com/zerocracy/farm/issues/1410
(requested by @ypshenychka to delete her contacts)

Updated join faq

---

_posts/2018/02/2018-02-22-policy.md

#80 - explained invite by not examiner

Invite by Zerocracy QA or PMO users

---

_posts/2018/06/2018-06-26-faq.md

#90 - removed outdated wallet command reference

Removed wallet command reference

---

_posts/2019/03/2019-03-28-cost-of-zerocrat.md

This word really is not in its place

Respect customers

---

_posts/2018/02/2018-02-22-policy.md

zerocracy/farm#1926 - changed refuse policy, penalty points depending on time of refusing

Changed refuse policy

---

_posts/2018/02/2018-02-22-policy.md

zerocracy/farm#2154 - take fee from projects without open source license

Fee for projects without open source license

---

_posts/2018/02/2018-02-22-policy.md

zerocracy/farm#2136 - using `application/x-www-form-urlencoded` webhook type in policy

Eplained webhook type
